services:
  vendure-server:
    image: vendure-server-docker:latest
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
  vendure-storefront-remix:
    image: vendure-storefront-remix-docker:latest
    ports:
      - 3000:3000