services:
  vendure-server:
    image: vendure-server-docker:latest
    ports: [ 3010:3010 ]
    networks: [ vendure-network ]
  vendure-storefront-remix:
    image: vendure-storefront-remix-docker:latest
    ports: [ 3000:3000, 8002:8002 ]
    networks: [ vendure-network ]
  vendure-storefront-vue:
    image: vendure-storefront-vue-docker:latest
    ports: [ 3001:3001 ]
    networks: [ vendure-network ]
  vendure-storefront-nextjs:
    image: vendure-storefront-nextjs-docker:latest
    ports: [ 3002:3000 ]
    networks: [ vendure-network ]
  vendure-storefront-angular:
    image: vendure-storefront-angular-docker:latest
    ports: [ 3003:4201 ]
    networks: [ vendure-network ]
networks:
  vendure-network:
    driver: bridge